FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY app.py /app/

#CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
# gunicorn --bind 0.0.0.0:8014 app:app
CMD ["gunicorn", "--bind", "0.0.0.0:8014", "app:app"]