apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-duckdb-pvc
spec:
  storageClassName: standard-nfs-production
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
